from __future__ import annotations

import json
import py_compile
from datetime import datetime
from pathlib import Path

from app.deepseek_assistant import DeepSeekMacroAssistant, DeepSeekMacroSuggestion
from app.generators.flange_generator import render_flange_body
from app.models import GeneratedDesign, PartSpec, SearchResult
from app.prompt_parser import MATERIAL_COLORS
from app.settings import MACROS_DIR, OUTPUT_DIR
from app.utils import ensure_dir, format_mm, slugify


class MacroGenerator:
    def __init__(
        self,
        macros_dir: Path = MACROS_DIR,
        output_dir: Path = OUTPUT_DIR,
        use_deepseek: bool = True,
    ) -> None:
        self.macros_dir = ensure_dir(macros_dir)
        self.output_dir = ensure_dir(output_dir)
        self.deepseek = DeepSeekMacroAssistant.from_env() if use_deepseek else None

    def generate(
        self,
        spec: PartSpec,
        rag_results: tuple[SearchResult, ...] = (),
    ) -> GeneratedDesign:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base_name = f"{timestamp}_{slugify(spec.prompt[:70])}"
        macro_path = self.macros_dir / f"{base_name}.py"
        output_paths = {
            "FCStd": self.output_dir / f"{base_name}.FCStd",
            "STEP": self.output_dir / f"{base_name}.step",
            "STL": self.output_dir / f"{base_name}.stl",
            "BREP": self.output_dir / f"{base_name}.brep",
            "OBJ": self.output_dir / f"{base_name}.obj",
            "metadata": self.output_dir / f"{base_name}_metadata.json",
            "build_report": self.output_dir / f"{base_name}_build_report.md",
            "thumbnail": self.output_dir / f"{base_name}_thumbnail.png",
        }
        deterministic_body = self.body_for_spec(spec)
        uses_local_template = spec.part_type in {"plate", "flange", "cylinder", "l_bracket", "box"}
        suggestion = self._deepseek_review(spec, rag_results, deterministic_body) if uses_local_template else self._deepseek_body(spec, rag_results, deterministic_body)
        llm_body_used = bool(suggestion and suggestion.body_code and not uses_local_template)
        llm_used = bool(suggestion)
        body = suggestion.body_code if llm_body_used and suggestion else deterministic_body
        llm_notes = suggestion.notes if suggestion else ""
        if uses_local_template:
            llm_notes = (
                f"{llm_notes} Gerador deterministico local usado para manter dimensoes validadas."
                if llm_notes
                else "DeepSeek nao disponivel; gerador deterministico local usado para manter dimensoes validadas."
            )
        llm_model = suggestion.model if suggestion else None
        code = self.render_macro(spec, base_name, rag_results, body, llm_used, llm_notes, llm_model)
        macro_path.write_text(code, encoding="utf-8")
        py_compile.compile(str(macro_path), doraise=True)
        summary = self.format_summary(spec, macro_path, output_paths, llm_used, llm_model, llm_notes)
        return GeneratedDesign(
            prompt=spec.prompt,
            spec=spec,
            macro_code=code,
            macro_path=macro_path,
            output_paths=output_paths,
            rag_results=rag_results,
            summary=summary,
            llm_used=llm_used,
            llm_model=llm_model,
            llm_notes=llm_notes,
        )

    def render_macro(
        self,
        spec: PartSpec,
        base_name: str,
        rag_results: tuple[SearchResult, ...] = (),
        body: str | None = None,
        llm_used: bool = False,
        llm_notes: str = "",
        llm_model: str | None = None,
    ) -> str:
        body = body or self.body_for_spec(spec)
        llm_header = (
            f"# DeepSeek assistance: enabled with {llm_model}\n# Notes: {llm_notes}"
            if llm_used
            else f"# DeepSeek assistance: fallback/local generator\n# Notes: {llm_notes or 'DeepSeek not used.'}"
        )
        references = "\n".join(
            f"# - {result.title}: {result.url}" for result in rag_results[:5]
        ) or "# - Nenhuma referencia RAG recuperada."
        prompt_block = "\n".join(f"# {line}" for line in spec.prompt.splitlines())
        output_dir = json.dumps(str(self.output_dir))
        base_name_literal = json.dumps(base_name)
        material = json.dumps(spec.material or "")
        color = MATERIAL_COLORS.get(spec.material or "", (0.70, 0.70, 0.70))
        color_literal = repr(tuple(float(part) for part in color))

        indented_body = self._indent(body, 4)
        spec_json = json.dumps(spec.to_dict(), ensure_ascii=False, indent=2)
        common = f'''# Generated by FreeCAD Prompt Forge
# Prompt:
{prompt_block}
#
{llm_header}
#
# RAG references:
{references}

import math
import os
import json
import traceback

import FreeCAD as App
import Part
from FreeCAD import Vector

DOC_NAME = "PromptForgePart"
BASE_NAME = {base_name_literal}
DEFAULT_OUTPUT_DIR = {output_dir}
MATERIAL_NAME = {material}
MATERIAL_COLOR = {color_literal}
PART_SPEC = {spec_json!r}


def log(message):
    print("[PromptForge]", message)


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)
    return path


def add_shape(doc, name, shape):
    obj = doc.addObject("Part::Feature", name)
    obj.Shape = shape
    try:
        obj.Label = name
        if MATERIAL_NAME:
            obj.Material = {{"Name": MATERIAL_NAME}}
        if hasattr(obj, "ViewObject") and obj.ViewObject:
            obj.ViewObject.ShapeColor = MATERIAL_COLOR
    except Exception as exc:
        log(f"Visual material skipped: {{exc}}")
    return obj


def cut_cylinder(shape, radius, height, base, direction):
    tool = Part.makeCylinder(radius, height, base, direction)
    return shape.cut(tool)


def safe_fillet(shape, radius):
    if radius <= 0:
        return shape
    try:
        return shape.makeFillet(radius, shape.Edges)
    except Exception as exc:
        log(f"Fillet skipped: {{exc}}")
        return shape


def safe_chamfer(shape, distance):
    if distance <= 0:
        return shape
    try:
        return shape.makeChamfer(distance, shape.Edges)
    except Exception as exc:
        log(f"Chamfer skipped: {{exc}}")
    return shape


def validate_shape(shape, name):
    info = {{"name": name, "valid": False, "volume": 0.0, "area": 0.0, "faces": 0, "edges": 0, "solids": 0, "bbox": {{}}}}
    try:
        if shape is None or shape.isNull():
            raise ValueError(name + " is null")
        try:
            shape = shape.removeSplitter()
        except Exception as exc:
            log(f"removeSplitter skipped for {{name}}: {{exc}}")
        valid = bool(shape.isValid())
        if not valid:
            try:
                shape.fix(0.01, 0.01, 0.01)
                valid = bool(shape.isValid())
            except Exception as exc:
                log(f"shape.fix skipped for {{name}}: {{exc}}")
        bbox = shape.BoundBox
        info.update(
            {{
                "valid": valid,
                "volume": float(getattr(shape, "Volume", 0.0)),
                "area": float(getattr(shape, "Area", 0.0)),
                "faces": len(getattr(shape, "Faces", [])),
                "edges": len(getattr(shape, "Edges", [])),
                "solids": len(getattr(shape, "Solids", [])),
                "bbox": {{
                    "x_length": float(bbox.XLength),
                    "y_length": float(bbox.YLength),
                    "z_length": float(bbox.ZLength),
                    "xmin": float(bbox.XMin),
                    "ymin": float(bbox.YMin),
                    "zmin": float(bbox.ZMin),
                    "xmax": float(bbox.XMax),
                    "ymax": float(bbox.YMax),
                    "zmax": float(bbox.ZMax),
                }},
            }}
        )
        if not valid:
            log(f"WARNING: {{name}} is invalid after repair attempts")
        return shape, info
    except Exception:
        log("Validation failed:\\n" + traceback.format_exc())
        raise


def export_outputs(doc, obj):
    output_dir = os.environ.get("PROMPT_FORGE_OUTPUT", DEFAULT_OUTPUT_DIR)
    ensure_dir(output_dir)
    fcstd_path = os.path.join(output_dir, BASE_NAME + ".FCStd")
    step_path = os.path.join(output_dir, BASE_NAME + ".step")
    stl_path = os.path.join(output_dir, BASE_NAME + ".stl")
    brep_path = os.path.join(output_dir, BASE_NAME + ".brep")
    obj_path = os.path.join(output_dir, BASE_NAME + ".obj")
    metadata_path = os.path.join(output_dir, BASE_NAME + "_metadata.json")
    report_path = os.path.join(output_dir, BASE_NAME + "_build_report.md")
    canonical_metadata_path = os.path.join(output_dir, "metadata.json")
    canonical_report_path = os.path.join(output_dir, "build_report.md")
    thumbnail_path = os.path.join(output_dir, BASE_NAME + "_thumbnail.png")
    shape, validation = validate_shape(obj.Shape, obj.Name)
    obj.Shape = shape
    doc.recompute()
    doc.saveAs(fcstd_path)
    export_errors = []
    try:
        Part.export([obj], step_path)
    except Exception:
        error = "STEP export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    try:
        import Mesh

        Mesh.export([obj], stl_path)
    except Exception:
        error = "STL export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    try:
        shape.exportBrep(brep_path)
    except Exception:
        error = "BREP export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    try:
        import Mesh

        Mesh.export([obj], obj_path)
    except Exception:
        error = "OBJ export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    if os.environ.get("PROMPT_FORGE_RENDER_THUMBNAIL") == "1":
        try:
            import FreeCADGui as Gui

            Gui.showMainWindow()
            Gui.ActiveDocument.ActiveView.viewIsometric()
            Gui.ActiveDocument.ActiveView.fitAll()
            Gui.ActiveDocument.ActiveView.saveImage(thumbnail_path, 1200, 900, "White")
        except Exception as exc:
            log(f"Thumbnail skipped: {{exc}}")
    else:
        log("Thumbnail skipped: PROMPT_FORGE_RENDER_THUMBNAIL not enabled for headless run")
    metadata = {{
        "base_name": BASE_NAME,
        "document": DOC_NAME,
        "material": MATERIAL_NAME,
        "part_spec": json.loads(PART_SPEC),
        "validation": validation,
        "files": {{
            "FCStd": fcstd_path,
            "STEP": step_path,
            "STL": stl_path,
            "BREP": brep_path,
            "OBJ": obj_path,
            "thumbnail": thumbnail_path if os.path.exists(thumbnail_path) else None,
        }},
        "export_errors": export_errors,
    }}
    with open(metadata_path, "w", encoding="utf-8") as handle:
        json.dump(metadata, handle, ensure_ascii=False, indent=2)
    with open(canonical_metadata_path, "w", encoding="utf-8") as handle:
        json.dump(metadata, handle, ensure_ascii=False, indent=2)
    with open(report_path, "w", encoding="utf-8") as handle:
        handle.write("# Build Report\\n\\n")
        handle.write(f"Base name: {{BASE_NAME}}\\n\\n")
        handle.write(f"Material: {{MATERIAL_NAME or 'not set'}}\\n\\n")
        handle.write("## Validation\\n\\n")
        handle.write(json.dumps(validation, ensure_ascii=False, indent=2))
        handle.write("\\n\\n## Files\\n\\n")
        for key, value in metadata["files"].items():
            handle.write(f"- {{key}}: {{value}}\\n")
        if export_errors:
            handle.write("\\n## Export Errors\\n\\n")
            for error in export_errors:
                handle.write("```text\\n" + error + "\\n```\\n")
    with open(canonical_report_path, "w", encoding="utf-8") as handle:
        with open(report_path, "r", encoding="utf-8") as source:
            handle.write(source.read())
    log("Saved: " + fcstd_path)
    log("Saved: " + step_path)
    log("Saved: " + stl_path)
    log("Saved: " + brep_path)
    log("Saved: " + obj_path)
    log("Saved: " + metadata_path)
    log("Saved: " + report_path)
    log("Saved: " + canonical_metadata_path)
    log("Saved: " + canonical_report_path)


def main():
    doc = App.newDocument(DOC_NAME)
'''
        tail = '''
    shape, validation = validate_shape(shape, "GeneratedShape")
    obj = add_shape(doc, "GeneratedPart", shape)
    export_outputs(doc, obj)


if __name__ == "__main__":
    main()
else:
    main()
'''
        return "\n\n".join([common.strip(), indented_body.rstrip(), tail.rstrip()]) + "\n"

    def _indent(self, code: str, spaces: int) -> str:
        prefix = " " * spaces
        return "\n".join((prefix + line if line.strip() else line) for line in code.splitlines())

    def body_for_spec(self, spec: PartSpec) -> str:
        return {
            "plate": self._plate_body,
            "flange": self._flange_body,
            "cylinder": self._cylinder_body,
            "l_bracket": self._l_bracket_body,
            "box": self._box_body,
        }[spec.part_type](spec)

    def _deepseek_body(
        self,
        spec: PartSpec,
        rag_results: tuple[SearchResult, ...],
        deterministic_body: str,
    ) -> DeepSeekMacroSuggestion | None:
        if not self.deepseek:
            return None
        suggestion = self.deepseek.suggest_body(spec, rag_results, deterministic_body)
        if suggestion and suggestion.body_code:
            return suggestion
        return suggestion

    def _deepseek_review(
        self,
        spec: PartSpec,
        rag_results: tuple[SearchResult, ...],
        deterministic_body: str,
    ) -> DeepSeekMacroSuggestion | None:
        if not self.deepseek:
            return None
        return self.deepseek.review_spec(spec, rag_results, deterministic_body)

    def format_summary(
        self,
        spec: PartSpec,
        macro_path: Path,
        output_paths: dict[str, Path],
        llm_used: bool = False,
        llm_model: str | None = None,
        llm_notes: str = "",
    ) -> str:
        dims = ", ".join(f"{key}={format_mm(value)} mm" for key, value in sorted(spec.dimensions.items()))
        features = ", ".join(feature.kind for feature in spec.features) or "sem recursos extras"
        assumptions = "\n".join(f"- {item}" for item in spec.assumptions) or "- Nenhuma suposicao extra."
        warnings = "\n".join(f"- {item}" for item in spec.warnings) or "- Nenhum aviso."
        outputs = "\n".join(f"- {kind}: {path}" for kind, path in output_paths.items())
        return (
            f"Tipo: {spec.part_type}\n"
            f"Material: {spec.material or 'nao informado'}\n"
            f"Dimensoes: {dims}\n"
            f"Recursos: {features}\n"
            f"DeepSeek: {'usado' if llm_used else 'nao usado/fallback'}"
            f"{f' ({llm_model})' if llm_model else ''}\n"
            f"Notas DeepSeek: {llm_notes or 'sem notas'}\n"
            f"Macro: {macro_path}\n\n"
            f"Arquivos esperados:\n{outputs}\n\n"
            f"Suposicoes:\n{assumptions}\n\n"
            f"Avisos:\n{warnings}"
        )

    def _feature(self, spec: PartSpec, kind: str):
        return spec.feature(kind)

    def _holes(self, spec: PartSpec) -> tuple[int, float, str]:
        feature = self._feature(spec, "holes") or self._feature(spec, "bolt_circle_holes")
        if not feature:
            return 0, spec.dimensions.get("hole_diameter", 6.0), "default"
        return (
            int(feature.params.get("count", 0)),
            float(feature.params.get("diameter", spec.dimensions.get("hole_diameter", 6.0))),
            str(feature.params.get("placement", "default")),
        )

    def _plate_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        length, width, thickness = d["length"], d["width"], d["thickness"]
        hole_count, hole_diameter, placement = self._holes(spec)
        margin = min(d.get("margin", 10.0), length / 2.5, width / 2.5)
        hole_points = self._rect_holes(length, width, hole_count, margin, placement)
        lines = [f"shape = Part.makeBox({format_mm(length)}, {format_mm(width)}, {format_mm(thickness)}, Vector(0, 0, 0))"]
        for x, y in hole_points:
            lines.append(
                f"shape = cut_cylinder(shape, {format_mm(hole_diameter / 2)}, {format_mm(thickness + 2)}, "
                f"Vector({format_mm(x)}, {format_mm(y)}, -1), Vector(0, 0, 1))"
            )
        slot = self._feature(spec, "slot")
        if slot:
            slot_length = float(slot.params["length"])
            slot_width = float(slot.params["width"])
            lines.extend(self._slot_cut_lines(slot_length, slot_width, thickness, length / 2, width / 2))
        lines.append(self._finish_edges(spec))
        return "\n".join(line for line in lines if line)

    def _flange_body(self, spec: PartSpec) -> str:
        lines = [render_flange_body(spec), self._finish_edges(spec)]
        return "\n".join(line for line in lines if line)

    def _cylinder_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        diameter, length = d["diameter"], d["length"]
        lines = [
            f"shape = Part.makeCylinder({format_mm(diameter / 2)}, {format_mm(length)}, Vector(0, 0, 0), Vector(0, 0, 1))",
            self._finish_edges(spec),
        ]
        return "\n".join(line for line in lines if line)

    def _l_bracket_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        length, width, height, thickness = d["length"], d["width"], d["height"], d["thickness"]
        hole_count, hole_diameter, placement = self._holes(spec)
        margin = min(d.get("margin", 10.0), length / 3, width / 3, height / 3)
        lines = [
            f"base = Part.makeBox({format_mm(length)}, {format_mm(width)}, {format_mm(thickness)}, Vector(0, 0, 0))",
            f"vertical = Part.makeBox({format_mm(thickness)}, {format_mm(width)}, {format_mm(height)}, Vector(0, 0, {format_mm(thickness)}))",
            "shape = base.fuse(vertical)",
        ]
        if hole_count:
            base_count = max(1, hole_count // 2) if placement == "tabs" else min(hole_count, 2)
            vertical_count = max(1, hole_count - base_count) if placement == "tabs" else max(0, hole_count - base_count)
            for x, y in self._rect_holes(length, width, base_count, margin, "default"):
                lines.append(
                    f"shape = cut_cylinder(shape, {format_mm(hole_diameter / 2)}, {format_mm(thickness + 2)}, "
                    f"Vector({format_mm(x)}, {format_mm(y)}, -1), Vector(0, 0, 1))"
                )
            for _, y in self._rect_holes(height, width, vertical_count, margin, "default"):
                z = margin if vertical_count == 1 else y
                lines.append(
                    f"shape = cut_cylinder(shape, {format_mm(hole_diameter / 2)}, {format_mm(thickness + 2)}, "
                    f"Vector(-1, {format_mm(width / 2)}, {format_mm(thickness + z)}), Vector(1, 0, 0))"
                )
        lines.extend(self._rib_lines(length, width, height, thickness))
        lines.append(self._finish_edges(spec))
        return "\n".join(line for line in lines if line)

    def _box_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        length, width, height, wall = d["length"], d["width"], d["height"], d["wall"]
        lines = [f"shape = Part.makeBox({format_mm(length)}, {format_mm(width)}, {format_mm(height)}, Vector(0, 0, 0))"]
        if self._feature(spec, "hollow"):
            inner_length = length - 2 * wall
            inner_width = width - 2 * wall
            inner_height = height
            lines.append(
                f"inner = Part.makeBox({format_mm(inner_length)}, {format_mm(inner_width)}, {format_mm(inner_height)}, "
                f"Vector({format_mm(wall)}, {format_mm(wall)}, {format_mm(wall)}))"
            )
            lines.append("shape = shape.cut(inner)")
        lines.append(self._finish_edges(spec))
        return "\n".join(line for line in lines if line)

    def _finish_edges(self, spec: PartSpec) -> str:
        fillet = spec.feature("fillet")
        chamfer = spec.feature("chamfer")
        lines: list[str] = []
        if fillet:
            lines.append(f"shape = safe_fillet(shape, {format_mm(float(fillet.params.get('radius', 2.0)))})")
        if chamfer:
            lines.append(f"shape = safe_chamfer(shape, {format_mm(float(chamfer.params.get('distance', 1.0)))})")
        return "\n".join(lines)

    def _slot_cut_lines(
        self,
        slot_length: float,
        slot_width: float,
        thickness: float,
        center_x: float,
        center_y: float,
    ) -> list[str]:
        return [
            f"slot_width = {format_mm(slot_width)}",
            f"slot_length = {format_mm(slot_length)}",
            f"slot_height = {format_mm(thickness + 2)}",
            f"slot_x = {format_mm(center_x)}",
            f"slot_y = {format_mm(center_y)}",
            "straight = max(slot_length - slot_width, 0)",
            "slot = Part.makeBox(straight, slot_width, slot_height, Vector(slot_x - straight / 2, slot_y - slot_width / 2, -1))",
            "slot = slot.fuse(Part.makeCylinder(slot_width / 2, slot_height, Vector(slot_x - straight / 2, slot_y, -1), Vector(0, 0, 1)))",
            "slot = slot.fuse(Part.makeCylinder(slot_width / 2, slot_height, Vector(slot_x + straight / 2, slot_y, -1), Vector(0, 0, 1)))",
            "shape = shape.cut(slot)",
        ]

    def _rect_holes(
        self,
        length: float,
        width: float,
        count: int,
        margin: float,
        placement: str,
    ) -> list[tuple[float, float]]:
        if count <= 0:
            return []
        if count == 1:
            return [(length / 2, width / 2)]
        if count == 2:
            return [(margin, width / 2), (length - margin, width / 2)]
        corners = [
            (margin, margin),
            (length - margin, margin),
            (length - margin, width - margin),
            (margin, width - margin),
        ]
        if placement == "corners" or count <= 4:
            return corners[:count]
        points = corners[:]
        extra = count - 4
        for idx in range(extra):
            fraction = (idx + 1) / (extra + 1)
            points.append((margin + fraction * (length - 2 * margin), width / 2))
        return points

    def _rib_lines(self, length: float, width: float, height: float, thickness: float) -> list[str]:
        rib_width = min(max(thickness, 4.0), width * 0.18)
        y_positions = [max(thickness, width * 0.20), min(width - rib_width - thickness, width * 0.72)]
        span = min(length * 0.45, height * 0.65)
        rib_height = min(height * 0.70, length * 0.50)
        lines = [
            "def make_rib(y_pos):",
            "    wire = Part.makePolygon([",
            f"        Vector({format_mm(thickness)}, y_pos, {format_mm(thickness)}),",
            f"        Vector({format_mm(thickness + span)}, y_pos, {format_mm(thickness)}),",
            f"        Vector({format_mm(thickness)}, y_pos, {format_mm(thickness + rib_height)}),",
            f"        Vector({format_mm(thickness)}, y_pos, {format_mm(thickness)}),",
            "    ])",
            f"    return Part.Face(wire).extrude(Vector(0, {format_mm(rib_width)}, 0))",
        ]
        for y in y_positions:
            lines.append(f"shape = shape.fuse(make_rib({format_mm(y)}))")
        return lines
