from __future__ import annotations

import json
import py_compile
from datetime import datetime
from pathlib import Path

from app.deepseek_assistant import DeepSeekMacroAssistant, DeepSeekMacroSuggestion
from app.generators.flange_generator import render_flange_body
from app.models import GeneratedDesign, PartSpec, SearchResult
from app.prompt_parser import MATERIAL_COLORS
from app.settings import MACROS_DIR, OUTPUT_DIR
from app.utils import ensure_dir, format_mm, slugify


class MacroGenerator:
    def __init__(
        self,
        macros_dir: Path = MACROS_DIR,
        output_dir: Path = OUTPUT_DIR,
        use_deepseek: bool = True,
    ) -> None:
        self.macros_dir = ensure_dir(macros_dir)
        self.output_dir = ensure_dir(output_dir)
        self.deepseek = DeepSeekMacroAssistant.from_env() if use_deepseek else None

    def generate(
        self,
        spec: PartSpec,
        rag_results: tuple[SearchResult, ...] = (),
    ) -> GeneratedDesign:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base_name = f"{timestamp}_{slugify(spec.prompt[:70])}"
        macro_path = self.macros_dir / f"{base_name}.py"
        output_paths = {
            "FCStd": self.output_dir / f"{base_name}.FCStd",
            "STEP": self.output_dir / f"{base_name}.step",
            "STL": self.output_dir / f"{base_name}.stl",
            "BREP": self.output_dir / f"{base_name}.brep",
            "OBJ": self.output_dir / f"{base_name}.obj",
            "topology": self.output_dir / f"{base_name}_topology.json",
            "metadata": self.output_dir / f"{base_name}_metadata.json",
            "build_report": self.output_dir / f"{base_name}_build_report.md",
            "thumbnail": self.output_dir / f"{base_name}_thumbnail.png",
        }
        deterministic_body = self.body_for_spec(spec)
        uses_local_template = spec.part_type in {"plate", "flange", "cylinder", "l_bracket", "box"}
        suggestion = self._deepseek_review(spec, rag_results, deterministic_body) if uses_local_template else self._deepseek_body(spec, rag_results, deterministic_body)
        llm_body_used = bool(suggestion and suggestion.body_code and not uses_local_template)
        llm_used = bool(suggestion)
        body = suggestion.body_code if llm_body_used and suggestion else deterministic_body
        llm_notes = suggestion.notes if suggestion else ""
        if uses_local_template:
            llm_notes = (
                f"{llm_notes} Gerador deterministico local usado para manter dimensoes validadas."
                if llm_notes
                else "DeepSeek nao disponivel; gerador deterministico local usado para manter dimensoes validadas."
            )
        llm_model = suggestion.model if suggestion else None
        code = self.render_macro(spec, base_name, rag_results, body, llm_used, llm_notes, llm_model)
        macro_path.write_text(code, encoding="utf-8")
        py_compile.compile(str(macro_path), doraise=True)
        summary = self.format_summary(spec, macro_path, output_paths, llm_used, llm_model, llm_notes)
        return GeneratedDesign(
            prompt=spec.prompt,
            spec=spec,
            macro_code=code,
            macro_path=macro_path,
            output_paths=output_paths,
            rag_results=rag_results,
            summary=summary,
            llm_used=llm_used,
            llm_model=llm_model,
            llm_notes=llm_notes,
        )

    def render_macro(
        self,
        spec: PartSpec,
        base_name: str,
        rag_results: tuple[SearchResult, ...] = (),
        body: str | None = None,
        llm_used: bool = False,
        llm_notes: str = "",
        llm_model: str | None = None,
    ) -> str:
        body = body or self.body_for_spec(spec)
        llm_header = (
            f"# DeepSeek assistance: enabled with {llm_model}\n# Notes: {llm_notes}"
            if llm_used
            else f"# DeepSeek assistance: fallback/local generator\n# Notes: {llm_notes or 'DeepSeek not used.'}"
        )
        references = "\n".join(
            f"# - {result.title}: {result.url}" for result in rag_results[:5]
        ) or "# - Nenhuma referencia RAG recuperada."
        prompt_block = "\n".join(f"# {line}" for line in spec.prompt.splitlines())
        output_dir = json.dumps(str(self.output_dir))
        base_name_literal = json.dumps(base_name)
        material = json.dumps(spec.material or "")
        color = MATERIAL_COLORS.get(spec.material or "", (0.70, 0.70, 0.70))
        color_literal = repr(tuple(float(part) for part in color))

        indented_body = self._indent(body, 4)
        spec_json = json.dumps(spec.to_dict(), ensure_ascii=False, indent=2)
        common = f'''# Generated by FreeCAD Prompt Forge
# Prompt:
{prompt_block}
#
{llm_header}
#
# RAG references:
{references}

import math
import os
import json
import traceback

import FreeCAD as App
import Part
from FreeCAD import Vector

DOC_NAME = "PromptForgePart"
BASE_NAME = {base_name_literal}
DEFAULT_OUTPUT_DIR = {output_dir}
MATERIAL_NAME = {material}
MATERIAL_COLOR = {color_literal}
PART_SPEC = {spec_json!r}


def log(message):
    print("[PromptForge]", message)


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)
    return path


BUILD_STEPS = []


def step_name(prefix):
    safe = "".join(ch if ch.isalnum() else "_" for ch in str(prefix)).strip("_") or "Step"
    return f"{{len(BUILD_STEPS) + 1:03d}}_{{safe}}"


def record_shape(name, shape, role="step", operation="", visible=False):
    BUILD_STEPS.append({{"name": step_name(name), "shape": shape, "role": role, "operation": operation, "visible": bool(visible)}})
    return shape


def add_shape(doc, name, shape, container=None, role="shape", operation="", visible=True):
    obj = doc.addObject("Part::Feature", name)
    obj.Shape = shape
    try:
        obj.Label = name
        obj.addProperty("App::PropertyString", "PromptForgeRole", "PromptForge", "Prompt Forge role")
        obj.PromptForgeRole = str(role)
        obj.addProperty("App::PropertyString", "PromptForgeOperation", "PromptForge", "Prompt Forge operation")
        obj.PromptForgeOperation = str(operation or "")
        if MATERIAL_NAME:
            obj.Material = {{"Name": MATERIAL_NAME}}
        if hasattr(obj, "ViewObject") and obj.ViewObject:
            obj.ViewObject.ShapeColor = MATERIAL_COLOR
            obj.ViewObject.Visibility = bool(visible)
            if not visible and role in {{"tool", "construction", "intermediate"}}:
                obj.ViewObject.Transparency = 75
            try:
                obj.ViewObject.DisplayMode = "Flat Lines"
            except Exception:
                pass
        if container is not None:
            try:
                container.addObject(obj)
            except Exception as exc:
                log(f"Could not add {{name}} to container: {{exc}}")
    except Exception as exc:
        log(f"Visual material skipped: {{exc}}")
    return obj


def apply_cut(source, tool, name="Cut"):
    record_shape(name + "_Tool", tool, role="tool", operation="subtract", visible=False)
    result = source.cut(tool)
    return record_shape(name + "_Result", result, role="intermediate", operation="cut", visible=False)


def apply_fuse(source, tool, name="Fuse"):
    record_shape(name + "_Tool", tool, role="tool", operation="add", visible=False)
    result = source.fuse(tool)
    return record_shape(name + "_Result", result, role="intermediate", operation="fuse", visible=False)


def cut_cylinder(shape, radius, height, base, direction, name="CylinderCut"):
    tool = Part.makeCylinder(radius, height, base, direction)
    return apply_cut(shape, tool, name)


def safe_fillet(shape, radius):
    if radius <= 0:
        return shape
    try:
        return record_shape("Fillet", shape.makeFillet(radius, shape.Edges), role="intermediate", operation="fillet", visible=False)
    except Exception as exc:
        log(f"Fillet skipped: {{exc}}")
        return shape


def safe_chamfer(shape, distance):
    if distance <= 0:
        return shape
    try:
        return record_shape("Chamfer", shape.makeChamfer(distance, shape.Edges), role="intermediate", operation="chamfer", visible=False)
    except Exception as exc:
        log(f"Chamfer skipped: {{exc}}")
    return shape


def create_project_tree(doc, final_shape):
    try:
        project = doc.addObject("App::DocumentObjectGroup", "PromptForge_Project")
        project.Label = "PromptForge Project"
    except Exception as exc:
        log(f"Project group unavailable; falling back to document root: {{exc}}")
        project = None
    try:
        history = doc.addObject("App::DocumentObjectGroup", "Construction_History")
        history.Label = "Construction History"
        if project is not None:
            project.addObject(history)
    except Exception as exc:
        log(f"History group unavailable; operation nodes will stay at document root: {{exc}}")
        history = None
    created = []
    for step in BUILD_STEPS:
        try:
            node = doc.addObject("App::FeaturePython", step.get("name", "BuildStep"))
            node.Label = step.get("name", "BuildStep")
            node.addProperty("App::PropertyString", "PromptForgeRole", "PromptForge", "Prompt Forge role")
            node.PromptForgeRole = str(step.get("role", "step"))
            node.addProperty("App::PropertyString", "PromptForgeOperation", "PromptForge", "Prompt Forge operation")
            node.PromptForgeOperation = str(step.get("operation", ""))
            shape_value = step.get("shape")
            if shape_value is not None:
                try:
                    bbox = shape_value.BoundBox
                    node.addProperty("App::PropertyString", "PromptForgeBBox", "PromptForge", "Bounding box")
                    node.PromptForgeBBox = json.dumps(bbox_payload(bbox), ensure_ascii=False)
                except Exception:
                    pass
            if history is not None:
                history.addObject(node)
            created.append(node)
        except Exception as exc:
            log(f"Could not create tree node {{step.get('name')}}: {{exc}}")
    final_obj = add_shape(
        doc,
        "Final_GeneratedPart",
        final_shape,
        container=None,
        role="final",
        operation="result",
        visible=True,
    )
    try:
        if hasattr(final_obj, "ViewObject") and final_obj.ViewObject:
            final_obj.ViewObject.ShapeColor = MATERIAL_COLOR
            final_obj.ViewObject.Visibility = True
    except Exception as exc:
        log(f"Tree visibility skipped: {{exc}}")
    return final_obj, project, created


def validate_shape(shape, name):
    info = {{"name": name, "valid": False, "volume": 0.0, "area": 0.0, "faces": 0, "edges": 0, "solids": 0, "bbox": {{}}}}
    try:
        if shape is None or shape.isNull():
            raise ValueError(name + " is null")
        try:
            shape = shape.removeSplitter()
        except Exception as exc:
            log(f"removeSplitter skipped for {{name}}: {{exc}}")
        valid = bool(shape.isValid())
        if not valid:
            try:
                shape.fix(0.01, 0.01, 0.01)
                valid = bool(shape.isValid())
            except Exception as exc:
                log(f"shape.fix skipped for {{name}}: {{exc}}")
        bbox = shape.BoundBox
        info.update(
            {{
                "valid": valid,
                "volume": float(getattr(shape, "Volume", 0.0)),
                "area": float(getattr(shape, "Area", 0.0)),
                "faces": len(getattr(shape, "Faces", [])),
                "edges": len(getattr(shape, "Edges", [])),
                "solids": len(getattr(shape, "Solids", [])),
                "bbox": {{
                    "x_length": float(bbox.XLength),
                    "y_length": float(bbox.YLength),
                    "z_length": float(bbox.ZLength),
                    "xmin": float(bbox.XMin),
                    "ymin": float(bbox.YMin),
                    "zmin": float(bbox.ZMin),
                    "xmax": float(bbox.XMax),
                    "ymax": float(bbox.YMax),
                    "zmax": float(bbox.ZMax),
                }},
            }}
        )
        if not valid:
            log(f"WARNING: {{name}} is invalid after repair attempts")
        return shape, info
    except Exception:
        log("Validation failed:\\n" + traceback.format_exc())
        raise


def feature_metadata(spec_payload):
    dimensions = spec_payload.get("dimensions", {{}})
    features = []
    for feature in spec_payload.get("features", []):
        kind = feature.get("kind")
        params = dict(feature.get("params", {{}}))
        item = {{"kind": kind, **params}}
        if kind == "bolt_circle_holes":
            count = int(params.get("count", dimensions.get("hole_count", 0)) or 0)
            radius = float(params.get("radius", dimensions.get("bolt_circle_radius", 0.0)) or 0.0)
            diameter = float(params.get("diameter", dimensions.get("hole_diameter", 0.0)) or 0.0)
            item.update(
                {{
                    "count": count,
                    "diameter": diameter,
                    "radius": radius,
                    "diameter_pcd": float(params.get("diameter_primitive", dimensions.get("bolt_circle_diameter", radius * 2.0)) or radius * 2.0),
                    "positions": [
                        {{
                            "x": radius * math.cos(2.0 * math.pi * idx / count),
                            "y": radius * math.sin(2.0 * math.pi * idx / count),
                            "z": 0.0,
                        }}
                        for idx in range(count)
                    ]
                    if count > 0 and radius > 0
                    else [],
                }}
            )
        features.append(item)
    return features


def shape_metadata(validation):
    bbox = validation.get("bbox", {{}})
    return {{
        "valid": validation.get("valid"),
        "volume_mm3": validation.get("volume"),
        "area_mm2": validation.get("area"),
        "faces": validation.get("faces"),
        "edges": validation.get("edges"),
        "solids": validation.get("solids"),
        "bbox": {{
            "x": bbox.get("x_length"),
            "y": bbox.get("y_length"),
            "z": bbox.get("z_length"),
            "xmin": bbox.get("xmin"),
            "xmax": bbox.get("xmax"),
            "ymin": bbox.get("ymin"),
            "ymax": bbox.get("ymax"),
            "zmin": bbox.get("zmin"),
            "zmax": bbox.get("zmax"),
        }},
    }}


def vector_payload(value):
    return {{
        "x": float(getattr(value, "x", 0.0)),
        "y": float(getattr(value, "y", 0.0)),
        "z": float(getattr(value, "z", 0.0)),
    }}


def bbox_payload(bbox):
    return {{
        "x": float(getattr(bbox, "XLength", 0.0)),
        "y": float(getattr(bbox, "YLength", 0.0)),
        "z": float(getattr(bbox, "ZLength", 0.0)),
        "xmin": float(getattr(bbox, "XMin", 0.0)),
        "xmax": float(getattr(bbox, "XMax", 0.0)),
        "ymin": float(getattr(bbox, "YMin", 0.0)),
        "ymax": float(getattr(bbox, "YMax", 0.0)),
        "zmin": float(getattr(bbox, "ZMin", 0.0)),
        "zmax": float(getattr(bbox, "ZMax", 0.0)),
    }}


def curve_payload(edge):
    payload = {{"type": "unknown"}}
    try:
        curve = edge.Curve
        payload["type"] = str(getattr(curve, "TypeId", curve.__class__.__name__))
        if hasattr(curve, "Radius"):
            payload["radius"] = float(curve.Radius)
            payload["diameter"] = float(curve.Radius) * 2.0
        if hasattr(curve, "Center"):
            payload["center"] = vector_payload(curve.Center)
        if hasattr(curve, "Axis"):
            payload["axis"] = vector_payload(curve.Axis)
    except Exception as exc:
        payload["error"] = str(exc)
    return payload


def surface_payload(face):
    payload = {{"type": "unknown"}}
    try:
        surface = face.Surface
        payload["type"] = str(getattr(surface, "TypeId", surface.__class__.__name__))
        if hasattr(surface, "Radius"):
            payload["radius"] = float(surface.Radius)
        if hasattr(surface, "Center"):
            payload["center"] = vector_payload(surface.Center)
        if hasattr(surface, "Axis"):
            payload["axis"] = vector_payload(surface.Axis)
    except Exception as exc:
        payload["error"] = str(exc)
    return payload


def face_normal(face):
    try:
        u_min, u_max, v_min, v_max = face.ParameterRange
        return vector_payload(face.normalAt((u_min + u_max) / 2.0, (v_min + v_max) / 2.0))
    except Exception:
        return None


def face_mesh_payload(face, tolerance=0.35):
    try:
        vertices, triangles = face.tessellate(tolerance)
        return {{
            "vertices": [[float(v.x), float(v.y), float(v.z)] for v in vertices],
            "triangles": [[int(i), int(j), int(k)] for i, j, k in triangles],
        }}
    except Exception as exc:
        return {{"vertices": [], "triangles": [], "error": str(exc)}}


def edge_points_payload(edge, count=96):
    try:
        points = edge.discretize(Number=count)
        return [[float(p.x), float(p.y), float(p.z)] for p in points]
    except Exception as exc:
        return {{"error": str(exc), "points": []}}


def topology_metadata(shape, metadata, topology_path, canonical_topology_path):
    topology = {{
        "units": "mm",
        "base_name": BASE_NAME,
        "source": "FreeCAD Part.Shape",
        "source_files": {{
            "FCStd": metadata["files"].get("FCStd"),
            "STEP": metadata["files"].get("STEP"),
            "BREP": metadata["files"].get("BREP"),
        }},
        "part_type": metadata.get("part_type"),
        "parameters": metadata.get("parameters", {{}}),
        "features": metadata.get("features", []),
        "shape": metadata.get("shape", {{}}),
        "faces": [],
        "edges": [],
    }}
    for index, face in enumerate(getattr(shape, "Faces", []), start=1):
        mesh = face_mesh_payload(face)
        topology["faces"].append(
            {{
                "id": index,
                "area": float(getattr(face, "Area", 0.0)),
                "center": vector_payload(getattr(face, "CenterOfMass", App.Vector(0, 0, 0))),
                "normal": face_normal(face),
                "surface": surface_payload(face),
                "bbox": bbox_payload(face.BoundBox),
                "mesh": mesh,
            }}
        )
    for index, edge in enumerate(getattr(shape, "Edges", []), start=1):
        curve = curve_payload(edge)
        topology["edges"].append(
            {{
                "id": index,
                "length": float(getattr(edge, "Length", 0.0)),
                "curve": curve,
                "is_circular": "radius" in curve,
                "bbox": bbox_payload(edge.BoundBox),
                "points": edge_points_payload(edge),
            }}
        )
    with open(topology_path, "w", encoding="utf-8") as handle:
        json.dump(topology, handle, ensure_ascii=False, indent=2)
    with open(canonical_topology_path, "w", encoding="utf-8") as handle:
        json.dump(topology, handle, ensure_ascii=False, indent=2)
    return topology


def export_outputs(doc, obj, project_container=None, tree_objects=None):
    output_dir = os.environ.get("PROMPT_FORGE_OUTPUT", DEFAULT_OUTPUT_DIR)
    ensure_dir(output_dir)
    fcstd_path = os.path.join(output_dir, BASE_NAME + ".FCStd")
    step_path = os.path.join(output_dir, BASE_NAME + ".step")
    stl_path = os.path.join(output_dir, BASE_NAME + ".stl")
    brep_path = os.path.join(output_dir, BASE_NAME + ".brep")
    obj_path = os.path.join(output_dir, BASE_NAME + ".obj")
    topology_path = os.path.join(output_dir, BASE_NAME + "_topology.json")
    metadata_path = os.path.join(output_dir, BASE_NAME + "_metadata.json")
    report_path = os.path.join(output_dir, BASE_NAME + "_build_report.md")
    canonical_topology_path = os.path.join(output_dir, "topology.json")
    canonical_metadata_path = os.path.join(output_dir, "metadata.json")
    canonical_report_path = os.path.join(output_dir, "build_report.md")
    thumbnail_path = os.path.join(output_dir, BASE_NAME + "_thumbnail.png")
    shape, validation = validate_shape(obj.Shape, obj.Name)
    obj.Shape = shape
    doc.recompute()
    doc.saveAs(fcstd_path)
    export_errors = []
    try:
        Part.export([obj], step_path)
    except Exception:
        error = "STEP export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    try:
        import Mesh

        Mesh.export([obj], stl_path)
    except Exception:
        error = "STL export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    try:
        shape.exportBrep(brep_path)
    except Exception:
        error = "BREP export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    try:
        import Mesh

        Mesh.export([obj], obj_path)
    except Exception:
        error = "OBJ export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        log(error)
    if os.environ.get("PROMPT_FORGE_RENDER_THUMBNAIL") == "1":
        try:
            import FreeCADGui as Gui

            Gui.showMainWindow()
            Gui.ActiveDocument.ActiveView.viewIsometric()
            Gui.ActiveDocument.ActiveView.fitAll()
            Gui.ActiveDocument.ActiveView.saveImage(thumbnail_path, 1200, 900, "White")
        except Exception as exc:
            log(f"Thumbnail skipped: {{exc}}")
    else:
        log("Thumbnail skipped: PROMPT_FORGE_RENDER_THUMBNAIL not enabled for headless run")
    spec_payload = json.loads(PART_SPEC)
    parameters = dict(spec_payload.get("dimensions", {{}}))
    feature_payload = feature_metadata(spec_payload)
    shape_payload = shape_metadata(validation)
    tree_objects = list(tree_objects or [])
    tree_payload = []
    for tree_obj in [*tree_objects, obj]:
        try:
            tree_payload.append(
                {{
                    "name": tree_obj.Name,
                    "label": tree_obj.Label,
                    "type": tree_obj.TypeId,
                    "role": getattr(tree_obj, "PromptForgeRole", ""),
                    "operation": getattr(tree_obj, "PromptForgeOperation", ""),
                    "visible": bool(tree_obj.ViewObject.Visibility) if hasattr(tree_obj, "ViewObject") and tree_obj.ViewObject else None,
                }}
            )
        except Exception:
            pass
    metadata = {{
        "units": "mm",
        "base_name": BASE_NAME,
        "document": DOC_NAME,
        "part_type": spec_payload.get("part_type"),
        "material": MATERIAL_NAME,
        "input_prompt": {json.dumps(spec.prompt)},
        "parameters": parameters,
        "features": feature_payload,
        "freecad_standard": {{
            "target": "FreeCAD 1.1 FCStd document",
            "container": project_container.Name if project_container is not None else None,
            "container_type": project_container.TypeId if project_container is not None else None,
            "final_object": obj.Name,
            "project_tree": tree_payload,
        }},
        "shape": shape_payload,
        "part_spec": spec_payload,
        "validation": validation,
        "files": {{
            "FCStd": fcstd_path,
            "STEP": step_path,
            "STL": stl_path,
            "BREP": brep_path,
            "OBJ": obj_path,
            "topology": topology_path,
            "fcstd": fcstd_path,
            "step": step_path,
            "stl": stl_path,
            "brep": brep_path,
            "obj": obj_path,
            "topology_json": topology_path,
            "thumbnail": thumbnail_path if os.path.exists(thumbnail_path) else None,
        }},
        "export_errors": export_errors,
    }}
    try:
        topology = topology_metadata(shape, metadata, topology_path, canonical_topology_path)
        metadata["topology"] = {{
            "path": topology_path,
            "canonical_path": canonical_topology_path,
            "faces": len(topology.get("faces", [])),
            "edges": len(topology.get("edges", [])),
            "source": "FreeCAD Part.Shape",
        }}
    except Exception:
        error = "Topology export failed:\\n" + traceback.format_exc()
        export_errors.append(error)
        metadata["topology"] = {{"error": error}}
        log(error)
    with open(metadata_path, "w", encoding="utf-8") as handle:
        json.dump(metadata, handle, ensure_ascii=False, indent=2)
    with open(canonical_metadata_path, "w", encoding="utf-8") as handle:
        json.dump(metadata, handle, ensure_ascii=False, indent=2)
    with open(report_path, "w", encoding="utf-8") as handle:
        handle.write("# Build Report\\n\\n")
        handle.write(f"Base name: {{BASE_NAME}}\\n\\n")
        handle.write(f"Material: {{MATERIAL_NAME or 'not set'}}\\n\\n")
        handle.write("## Validation\\n\\n")
        handle.write(json.dumps(validation, ensure_ascii=False, indent=2))
        handle.write("\\n\\n## Files\\n\\n")
        for key, value in metadata["files"].items():
            handle.write(f"- {{key}}: {{value}}\\n")
        handle.write("\\n## FreeCAD Project Tree\\n\\n")
        handle.write(json.dumps(metadata.get("freecad_standard", {{}}), ensure_ascii=False, indent=2))
        handle.write("\\n")
        if metadata.get("topology"):
            handle.write("\\n## Topology\\n\\n")
            handle.write(json.dumps(metadata["topology"], ensure_ascii=False, indent=2))
            handle.write("\\n")
        if export_errors:
            handle.write("\\n## Export Errors\\n\\n")
            for error in export_errors:
                handle.write("```text\\n" + error + "\\n```\\n")
    with open(canonical_report_path, "w", encoding="utf-8") as handle:
        with open(report_path, "r", encoding="utf-8") as source:
            handle.write(source.read())
    log("Saved: " + fcstd_path)
    log("Saved: " + step_path)
    log("Saved: " + stl_path)
    log("Saved: " + brep_path)
    log("Saved: " + obj_path)
    if os.path.exists(topology_path):
        log("Saved: " + topology_path)
    if os.path.exists(canonical_topology_path):
        log("Saved: " + canonical_topology_path)
    log("Saved: " + metadata_path)
    log("Saved: " + report_path)
    log("Saved: " + canonical_metadata_path)
    log("Saved: " + canonical_report_path)


def main():
    doc = App.newDocument(DOC_NAME)
'''
        tail = '''
    shape, validation = validate_shape(shape, "GeneratedShape")
    obj, project_container, tree_objects = create_project_tree(doc, shape)
    export_outputs(doc, obj, project_container, tree_objects)


if __name__ == "__main__":
    main()
else:
    main()
'''
        return "\n\n".join([common.strip(), indented_body.rstrip(), tail.rstrip()]) + "\n"

    def _indent(self, code: str, spaces: int) -> str:
        prefix = " " * spaces
        return "\n".join((prefix + line if line.strip() else line) for line in code.splitlines())

    def body_for_spec(self, spec: PartSpec) -> str:
        return {
            "plate": self._plate_body,
            "flange": self._flange_body,
            "cylinder": self._cylinder_body,
            "l_bracket": self._l_bracket_body,
            "box": self._box_body,
        }[spec.part_type](spec)

    def _deepseek_body(
        self,
        spec: PartSpec,
        rag_results: tuple[SearchResult, ...],
        deterministic_body: str,
    ) -> DeepSeekMacroSuggestion | None:
        if not self.deepseek:
            return None
        suggestion = self.deepseek.suggest_body(spec, rag_results, deterministic_body)
        if suggestion and suggestion.body_code:
            return suggestion
        return suggestion

    def _deepseek_review(
        self,
        spec: PartSpec,
        rag_results: tuple[SearchResult, ...],
        deterministic_body: str,
    ) -> DeepSeekMacroSuggestion | None:
        if not self.deepseek:
            return None
        return self.deepseek.review_spec(spec, rag_results, deterministic_body)

    def format_summary(
        self,
        spec: PartSpec,
        macro_path: Path,
        output_paths: dict[str, Path],
        llm_used: bool = False,
        llm_model: str | None = None,
        llm_notes: str = "",
    ) -> str:
        dims = ", ".join(f"{key}={format_mm(value)} mm" for key, value in sorted(spec.dimensions.items()))
        features = ", ".join(feature.kind for feature in spec.features) or "sem recursos extras"
        assumptions = "\n".join(f"- {item}" for item in spec.assumptions) or "- Nenhuma suposicao extra."
        warnings = "\n".join(f"- {item}" for item in spec.warnings) or "- Nenhum aviso."
        outputs = "\n".join(f"- {kind}: {path}" for kind, path in output_paths.items())
        return (
            f"Tipo: {spec.part_type}\n"
            f"Material: {spec.material or 'nao informado'}\n"
            f"Dimensoes: {dims}\n"
            f"Recursos: {features}\n"
            f"DeepSeek: {'usado' if llm_used else 'nao usado/fallback'}"
            f"{f' ({llm_model})' if llm_model else ''}\n"
            f"Notas DeepSeek: {llm_notes or 'sem notas'}\n"
            f"Macro: {macro_path}\n\n"
            f"Arquivos esperados:\n{outputs}\n\n"
            f"Suposicoes:\n{assumptions}\n\n"
            f"Avisos:\n{warnings}"
        )

    def _feature(self, spec: PartSpec, kind: str):
        return spec.feature(kind)

    def _holes(self, spec: PartSpec) -> tuple[int, float, str]:
        feature = self._feature(spec, "holes") or self._feature(spec, "bolt_circle_holes")
        if not feature:
            return 0, spec.dimensions.get("hole_diameter", 6.0), "default"
        return (
            int(feature.params.get("count", 0)),
            float(feature.params.get("diameter", spec.dimensions.get("hole_diameter", 6.0))),
            str(feature.params.get("placement", "default")),
        )

    def _plate_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        length, width, thickness = d["length"], d["width"], d["thickness"]
        hole_count, hole_diameter, placement = self._holes(spec)
        margin = min(d.get("margin", 10.0), length / 2.5, width / 2.5)
        hole_points = self._rect_holes(length, width, hole_count, margin, placement)
        lines = [
            f"shape = record_shape('Base_Plate', Part.makeBox({format_mm(length)}, {format_mm(width)}, {format_mm(thickness)}, Vector(0, 0, 0)), role='base', operation='create', visible=False)"
        ]
        for index, (x, y) in enumerate(hole_points, start=1):
            lines.append(
                f"shape = cut_cylinder(shape, {format_mm(hole_diameter / 2)}, {format_mm(thickness + 2)}, "
                f"Vector({format_mm(x)}, {format_mm(y)}, -1), Vector(0, 0, 1), 'Hole_{index}')"
            )
        slot = self._feature(spec, "slot")
        if slot:
            slot_length = float(slot.params["length"])
            slot_width = float(slot.params["width"])
            lines.extend(self._slot_cut_lines(slot_length, slot_width, thickness, length / 2, width / 2))
        lines.extend(self._cad_operation_lines(spec))
        lines.append(self._finish_edges(spec))
        return "\n".join(line for line in lines if line)

    def _flange_body(self, spec: PartSpec) -> str:
        lines = [render_flange_body(spec), *self._cad_operation_lines(spec), self._finish_edges(spec)]
        return "\n".join(line for line in lines if line)

    def _cylinder_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        diameter, length = d["diameter"], d["length"]
        lines = [
            f"shape = record_shape('Base_Cylinder', Part.makeCylinder({format_mm(diameter / 2)}, {format_mm(length)}, Vector(0, 0, 0), Vector(0, 0, 1)), role='base', operation='create', visible=False)",
            *self._cad_operation_lines(spec),
            self._finish_edges(spec),
        ]
        return "\n".join(line for line in lines if line)

    def _l_bracket_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        length, width, height, thickness = d["length"], d["width"], d["height"], d["thickness"]
        hole_count, hole_diameter, placement = self._holes(spec)
        margin = min(d.get("margin", 10.0), length / 3, width / 3, height / 3)
        lines = [
            f"base = record_shape('L_Base_Flange', Part.makeBox({format_mm(length)}, {format_mm(width)}, {format_mm(thickness)}, Vector(0, 0, 0)), role='base', operation='create', visible=False)",
            f"vertical = Part.makeBox({format_mm(thickness)}, {format_mm(width)}, {format_mm(height)}, Vector(0, 0, {format_mm(thickness)}))",
            "shape = apply_fuse(base, vertical, 'L_Vertical_Flange')",
        ]
        if hole_count:
            base_count = max(1, hole_count // 2) if placement == "tabs" else min(hole_count, 2)
            vertical_count = max(1, hole_count - base_count) if placement == "tabs" else max(0, hole_count - base_count)
            for index, (x, y) in enumerate(self._rect_holes(length, width, base_count, margin, "default"), start=1):
                lines.append(
                    f"shape = cut_cylinder(shape, {format_mm(hole_diameter / 2)}, {format_mm(thickness + 2)}, "
                    f"Vector({format_mm(x)}, {format_mm(y)}, -1), Vector(0, 0, 1), 'Base_Hole_{index}')"
                )
            for index, (_, y) in enumerate(self._rect_holes(height, width, vertical_count, margin, "default"), start=1):
                z = margin if vertical_count == 1 else y
                lines.append(
                    f"shape = cut_cylinder(shape, {format_mm(hole_diameter / 2)}, {format_mm(thickness + 2)}, "
                    f"Vector(-1, {format_mm(width / 2)}, {format_mm(thickness + z)}), Vector(1, 0, 0), 'Vertical_Hole_{index}')"
                )
        lines.extend(self._rib_lines(length, width, height, thickness))
        lines.extend(self._cad_operation_lines(spec))
        lines.append(self._finish_edges(spec))
        return "\n".join(line for line in lines if line)

    def _box_body(self, spec: PartSpec) -> str:
        d = spec.dimensions
        length, width, height, wall = d["length"], d["width"], d["height"], d["wall"]
        lines = [
            f"shape = record_shape('Base_Box', Part.makeBox({format_mm(length)}, {format_mm(width)}, {format_mm(height)}, Vector(0, 0, 0)), role='base', operation='create', visible=False)"
        ]
        if self._feature(spec, "hollow"):
            inner_length = length - 2 * wall
            inner_width = width - 2 * wall
            inner_height = height
            lines.append(
                f"inner = Part.makeBox({format_mm(inner_length)}, {format_mm(inner_width)}, {format_mm(inner_height)}, "
                f"Vector({format_mm(wall)}, {format_mm(wall)}, {format_mm(wall)}))"
            )
            lines.append("shape = apply_cut(shape, inner, 'Hollow_Box')")
        lines.extend(self._cad_operation_lines(spec))
        lines.append(self._finish_edges(spec))
        return "\n".join(line for line in lines if line)

    def _cad_operation_lines(self, spec: PartSpec) -> list[str]:
        lines: list[str] = []
        for index, feature in enumerate((item for item in spec.features if item.kind == "cad_op"), start=1):
            params = feature.params
            op = str(params.get("op", "")).lower().replace("-", "_")

            def number(name: str, default: float) -> float:
                try:
                    return float(params.get(name, default))
                except (TypeError, ValueError):
                    return default

            x = number("x", 0.0)
            y = number("y", 0.0)
            z = number("z", 0.0)
            axis = str(params.get("axis", "z")).lower()
            direction = {
                "x": "Vector(1, 0, 0)",
                "y": "Vector(0, 1, 0)",
                "z": "Vector(0, 0, 1)",
            }.get(axis, "Vector(0, 0, 1)")
            tool_name = f"cad_tool_{index}"

            if op in {"add_box", "fuse_box", "subtract_box", "cut_box"}:
                length = number("length", number("l", 10.0))
                width = number("width", number("w", 10.0))
                height = number("height", number("h", spec.dimensions.get("thickness", 10.0)))
                lines.append(
                    f"{tool_name} = Part.makeBox({format_mm(length)}, {format_mm(width)}, {format_mm(height)}, "
                    f"Vector({format_mm(x)}, {format_mm(y)}, {format_mm(z)}))"
                )
                lines.append(
                    f"shape = apply_cut(shape, {tool_name}, 'CAD_{index}_{op}')"
                    if op.startswith(("subtract", "cut"))
                    else f"shape = apply_fuse(shape, {tool_name}, 'CAD_{index}_{op}')"
                )
                continue

            if op in {"add_cylinder", "fuse_cylinder", "subtract_cylinder", "cut_cylinder", "hole", "drill"}:
                diameter = number("diameter", number("dia", 6.0))
                height = number("height", number("depth", spec.dimensions.get("thickness", 10.0) + 2.0))
                lines.append(
                    f"{tool_name} = Part.makeCylinder({format_mm(diameter / 2.0)}, {format_mm(height)}, "
                    f"Vector({format_mm(x)}, {format_mm(y)}, {format_mm(z)}), {direction})"
                )
                cut = op.startswith(("subtract", "cut")) or op in {"hole", "drill"}
                lines.append(
                    f"shape = apply_cut(shape, {tool_name}, 'CAD_{index}_{op}')"
                    if cut
                    else f"shape = apply_fuse(shape, {tool_name}, 'CAD_{index}_{op}')"
                )
                continue

            lines.append(f"log('CAD_OP ignorada: {op}')")
        return lines

    def _finish_edges(self, spec: PartSpec) -> str:
        fillet = spec.feature("fillet")
        chamfer = spec.feature("chamfer")
        lines: list[str] = []
        if fillet:
            lines.append(f"shape = safe_fillet(shape, {format_mm(float(fillet.params.get('radius', 2.0)))})")
        if chamfer:
            lines.append(f"shape = safe_chamfer(shape, {format_mm(float(chamfer.params.get('distance', 1.0)))})")
        return "\n".join(lines)

    def _slot_cut_lines(
        self,
        slot_length: float,
        slot_width: float,
        thickness: float,
        center_x: float,
        center_y: float,
    ) -> list[str]:
        return [
            f"slot_width = {format_mm(slot_width)}",
            f"slot_length = {format_mm(slot_length)}",
            f"slot_height = {format_mm(thickness + 2)}",
            f"slot_x = {format_mm(center_x)}",
            f"slot_y = {format_mm(center_y)}",
            "straight = max(slot_length - slot_width, 0)",
            "slot = Part.makeBox(straight, slot_width, slot_height, Vector(slot_x - straight / 2, slot_y - slot_width / 2, -1))",
            "slot = slot.fuse(Part.makeCylinder(slot_width / 2, slot_height, Vector(slot_x - straight / 2, slot_y, -1), Vector(0, 0, 1)))",
            "slot = slot.fuse(Part.makeCylinder(slot_width / 2, slot_height, Vector(slot_x + straight / 2, slot_y, -1), Vector(0, 0, 1)))",
            "shape = apply_cut(shape, slot, 'Slot')",
        ]

    def _rect_holes(
        self,
        length: float,
        width: float,
        count: int,
        margin: float,
        placement: str,
    ) -> list[tuple[float, float]]:
        if count <= 0:
            return []
        if count == 1:
            return [(length / 2, width / 2)]
        if count == 2:
            return [(margin, width / 2), (length - margin, width / 2)]
        corners = [
            (margin, margin),
            (length - margin, margin),
            (length - margin, width - margin),
            (margin, width - margin),
        ]
        if placement == "corners" or count <= 4:
            return corners[:count]
        points = corners[:]
        extra = count - 4
        for idx in range(extra):
            fraction = (idx + 1) / (extra + 1)
            points.append((margin + fraction * (length - 2 * margin), width / 2))
        return points

    def _rib_lines(self, length: float, width: float, height: float, thickness: float) -> list[str]:
        rib_width = min(max(thickness, 4.0), width * 0.18)
        y_positions = [max(thickness, width * 0.20), min(width - rib_width - thickness, width * 0.72)]
        span = min(length * 0.45, height * 0.65)
        rib_height = min(height * 0.70, length * 0.50)
        lines = [
            "def make_rib(y_pos):",
            "    wire = Part.makePolygon([",
            f"        Vector({format_mm(thickness)}, y_pos, {format_mm(thickness)}),",
            f"        Vector({format_mm(thickness + span)}, y_pos, {format_mm(thickness)}),",
            f"        Vector({format_mm(thickness)}, y_pos, {format_mm(thickness + rib_height)}),",
            f"        Vector({format_mm(thickness)}, y_pos, {format_mm(thickness)}),",
            "    ])",
            f"    return Part.Face(wire).extrude(Vector(0, {format_mm(rib_width)}, 0))",
        ]
        for index, y in enumerate(y_positions, start=1):
            lines.append(f"shape = apply_fuse(shape, make_rib({format_mm(y)}), 'Rib_{index}')")
        return lines
